# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
 Store.create(name: 'Store 1', address: '100 East Main St', city: 'West Chicago', state: 'IL', zip: '61085', country: 'United States', area_code: '555', phone_1: '555', phone_2: '5555', description: 'this is the description', user_id: '1', website: 'www.website.com', store_type: 'dispensary', mon_open: '06:00', mon_end: '16:00', mon_closed: false, tues_open: '06:00', tues_end: '16:00', tues_closed: false, wed_open: '06:00', wed_end: '16:00', wed_closed: false, thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true, fri_open: '06:00', fri_end: '16:00', fri_closed: false, sat_open: '00:00', sat_end: '00:00', sat_closed: true, sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 2',
              address: '1761 NJ-27', city:'Edison', state: 'NJ', zip: '08817', country: 'United States',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'This is the Description',
              user_id: '1',
              website: 'www.website.com',
              store_type: 'Dispensary',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 3',
              address: '1000 Murray Ross Pkwy', city: 'North York', state: 'ON', zip: 'M3J 2P3', country:'Canada',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'This is the Description',
              user_id: '2',
              website: 'www.website.com',
              store_type: 'Brand',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 4',
              address: '129 Main St S', city:'Chatfield', state:'MN', zip:'55923', country:'United States',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'this is the description',
              user_id: '2',
              website: 'www.website.com',
              store_type: 'delivery',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 5',
              address: '28637 N Sunset Dr', city:'Queens Creek', state:'AZ', zip:'85143', country:'United States',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'This is the Description',
              user_id: '1',
              website: 'www.example.com',
              store_type: 'Brand',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 6',
              address:'7433 Edminds St', city: 'Burnaby', state: 'BC', zip:'V3N1B1', country: 'Canada',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'This is the Description',
              user_id: '2',
              website: 'www.example.com',
              store_type: 'Service',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)
 Store.create(name: 'Store 7',
              address:'6097 Bennett Valley Rd', city:'Santa Rosa', state: 'CA', zip:'95404', country:'United States',
              area_code: '555', phone_1: '555', phone_2: '5555',
              description: 'This is the Description',
              user_id: '2',
              website: 'www.example.com',
              store_type: 'Dispensary',
              mon_open: '06:00', mon_end: '16:00', mon_closed: false,
              tues_open: '06:00', tues_end: '16:00', tues_closed: false,
              wed_open: '06:00', wed_end: '16:00', wed_closed: false,
              thurs_open: '00:00', thurs_end: '00:00', thurs_closed: true,
              fri_open: '06:00', fri_end: '16:00', fri_closed: false,
              sat_open: '00:00', sat_end: '00:00', sat_closed: true,
              sun_open: '00:00', sun_end: '00:00', sun_closed: true)